### ISSUE TITLE
Built-in types and class names should be a different color in assignments

### ISSUE THREAD

**Issue by TwitchBronBron** [dotnet/csharp-tmLanguage#129] opened 2018-07-11 14:16 UTC
## Details
VSCode Version: 1.25.0
Theme: Dark+ (default dark)

## Repro
The built-in types and class names should color differently than regular variables when used in assignments.

This is how it currently looks: 

![image](https://user-images.githubusercontent.com/2544493/42576427-568beb96-84f0-11e8-82c4-f97b24ae8d24.png)

<details>
<summary>Source code</summary>

```C#
 public class SomeClass
    {
        public static int SomeValue = 10;
        public void ShowColorIssues(uint value)
        {
            value = int.MaxValue;
            value = uint.MaxValue;
            value = UInt16.MaxValue;

            SomeClass.SomeValue = 2;
            var someStaticValue = SomeClass.SomeValue;
        }
    }

```
</details>
<br/>

## What I expected to see
`int`, `uint`, `UInt16`, and `SomeClass` are all colored differently than "normal" variables because they are types or system objects. 

![image](https://user-images.githubusercontent.com/2544493/42576638-e30b3720-84f0-11e8-9d8e-6a88606ec43e.png)

**Comment by DustinCampbell** [comment] 2018-07-16 18:12
Hi! Thanks for filing this issue!

The problem you described with pre-defined keywords is tracked by https://github.com/dotnet/csharp-tmLanguage/issues/19.

For other types, we are restricted by what we can do because this colorizer is handled via regular expressions. From within a regular expression, we can't determine what `UInt16` or `SomeClass` actually are semantically. They could be fields, properties, types, other local variables, etc. -- there's no way to know. Eventually, we may have a VS Code API for providing semantic highlighting that would augment the regular expression colorization, but we don't have that today. This is a duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/71.

**Closed by DustinCampbell** 2018-07-16 18:12 UTC
Labels: Resolved-Duplicate
