### ISSUE TITLE
C# multiline function header syntax highlight problem

### ISSUE THREAD

**Issue by alexr00** [dotnet/csharp-tmLanguage#230] opened 2021-11-15 12:44 UTC
## Details

What editor are you seeing the problem in? (e.g. Atom, Visual Studio Code, etc.)
VS Code

What version of the editor are you using?
1.62

What color theme are you using?
N/A

## Repro

If I declare function with multiple lines in header, syntax highlight is broken
![image](https://user-images.githubusercontent.com/3390973/141345292-4f2b0240-c122-43f5-a309-84386faa6c2e.png)

Single-line function headers have correct highlight:
![image](https://user-images.githubusercontent.com/3390973/141345439-c0a6ebd2-4742-4358-87bf-5e9701b476b4.png)

simplest example with the problem:

```c#
using System;

namespace Test {
	class Test {
		public (int x, int y, int z)
		function(int a)
		{
			return (a, a, a);
		}

		public void foo()
		{
			var res = function(0);
			var x = res.x;
			var y = res.y;
			var z = res.z;
		}
	}
}
```

Originally from @vladtcvs in https://github.com/microsoft/vscode/issues/136977

**Comment by wise0704** [comment] 2023-08-08 10:56
Duplicate of #63

**Closed** 2023-08-08 21:24 UTC
Labels: Resolved-Duplicate
