### ISSUE TITLE
Broken syntax highlighting when using method parentheses in new line

### ISSUE THREAD

**Issue by rchande** [dotnet/csharp-tmLanguage#144] opened 2019-01-02 16:36 UTC
## Details

VS Code 1.30.1, C# extension 1.17.1

## Repro

```cs
public class Foo
{
    void Bar(
        object a,
        object b,
        object c,
        object d,
    )
    {
        // Works
       Console.WriteLine($"{a}, {b}, {c}, {d}");
    }   
}

public class Foo
{
    void Bar
    (
        object a,
        object b,
        object c,
        object d,
    )
    {
        // Don't work
       Console.WriteLine($"{a}, {b}, {c}, {d}");
    }   
}
```

**Comment by DustinCampbell** [comment] 2019-01-03 21:08
This is a duplicate of https://github.com/dotnet/csharp-tmLanguage/issues/63.

**Closed** 2019-01-03 21:08 UTC
Labels: Resolved-Duplicate
